# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fdb16d00b871cdfdc76bf9cefc6dea35649124159cbd68a31d1a773cdcbdfdd54f9c31235b81a459d27d33aabfb9bff6559e36867294cf28d17868c963a5b10

test:
  secret_key_base: 0c5ee57fddae6f4a9a2f7bb746ff99e3b0413e9ac5cfe691b301291ceb801b1c18786e9d9bf5c62c28092b4d4c98a693a84ebef657191a095c3f9ecce7b9bcd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
